---
apiVersion: 1
datasources:
  - access: proxy
    isDefault: false
    name: Jaeger
    type: jaeger
    uid: jaeger
    url: "http://jaeger:16686"
  - access: proxy
    isDefault: true
    name: Prometheus
    type: prometheus
    uid: prometheus
    url: "http://prometheus:9090"
